# Compose file odoo Ultranet v13.0 + https
# Ojo hay que crear el /odoo_ar/traefik/acme.json y ponerle chmod 600
# Version 2021-11-11
#################################################################################

version: '3.5'

services:
  traefik:
    image: traefik:2.3.7
    container_name: traefik
    restart: unless-stopped
    command:
      - --entrypoints.web.address=:80
      - --entryPoints.websecure.address=:443

      #- --log.level=DEBUG # Don't do that in production
      - --providers.docker
      # - --api.insecure # Don't do that in production
      # - --api.debug # Don't do that in production

      - --certificatesresolvers.le.acme.email=lbozzi@gmail.com
      - --certificatesresolvers.le.acme.storage=/opt/traefik/acme.json
      - --certificatesresolvers.le.acme.httpChallenge=true
      - --certificatesresolvers.le.acme.httpChallenge.entryPoint=web
      #- --certificatesresolvers.le.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory # descoment for staging
    ports:
      - "80:80"
      - "443:443"
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /odoo_ar/traefik/:/opt/traefik/

  postgres:
    image: postgres:12.10-alpine
    container_name: pg-infas
    restart: unless-stopped
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - ${PROJECT_PATH}/postgresql:/var/lib/postgresql/data

  odoo:
    image: ${ODOO_IMAGE}
    container_name: odoo
    restart: unless-stopped
    volumes:
      - ${PROJECT_PATH}/config:/opt/odoo/etc/
      - ${PROJECT_PATH}/data_dir:/opt/odoo/data
      - ${PROJECT_PATH}/log:/var/log/odoo
      - ${PROJECT_PATH}/sources:/opt/odoo/custom-addons
      - ${PROJECT_PATH}/backup_dir:/var/odoo/backups/
    links:
      - postgres:db
    environment:
      - SERVER_MODE=
    labels: 
      - traefik.enable=true
      #----------------------------------------------- routers for: odoo --------------------------------------------------
      # http
      - traefik.http.routers.odoo-http.rule=Host(`${SITE_DOMAIN}`)
      - traefik.http.routers.odoo-http.entrypoints=http
      #- traefik.http.routers.odoo-http.middlewares=redirect@file
      - traefik.http.routers.odoo-http.service=odoo
      # https
      - traefik.http.routers.odoo-https.rule=Host(`${SITE_DOMAIN}`)
      - traefik.http.routers.odoo-https.entrypoints=https
      - traefik.http.routers.odoo-https.service=odoo
      - traefik.http.routers.odoo-https.tls.certresolver=le
      - traefik.http.routers.odoo-https.middlewares=gzip,sslheader,limit
      #----------------------------- routes for: odoo/web/database || odoo/website/info  -----------------------------
      # http 
      - traefik.http.routers.odoo-db-http.rule=Host(`${SITE_DOMAIN}`) && (PathPrefix(`/web/database`) || PathPrefix(`/website/info`))
      - traefik.http.routers.odoo-db-http.entrypoints=http
      - traefik.http.routers.odoo-db-http.service=odoo
      #- traefik.http.routers.odoo-db-http.middlewares=redirect@file
      - traefik.http.services.odoo-db-http.loadbalancer.server.port=${ODOO_PORT}
      # https 
      - traefik.http.routers.odoo-db-https.rule=Host(`${SITE_DOMAIN}`) && (PathPrefix(`/web/database`) || PathPrefix(`/website/info`))
      - traefik.http.routers.odoo-db-https.entrypoints=https
      - traefik.http.routers.odoo-db-https.service=odoo
      - traefik.http.routers.odoo-db-https.tls.certresolver=le
      - traefik.http.routers.odoo-db-https.middlewares=gzip,sslheader,limit
      - traefik.http.services.odoo-db-https.loadbalancer.server.port=${ODOO_PORT}
      #---------------------------------------- routes for: odoo/longpolling ------------------------------------------------
      # http 
      - traefik.http.routers.odoo-im-http.rule=Host(`${SITE_DOMAIN}`) && (PathPrefix(`/longpolling`))
      - traefik.http.routers.odoo-im-http.entrypoints=http
      #- traefik.http.routers.odoo-im-http.middlewares=redirect@file
      - traefik.http.routers.odoo-im-http.service=odoo-im
      # https 
      - traefik.http.routers.odoo-im-https.rule=Host(`${SITE_DOMAIN}`) && (PathPrefix(`/longpolling`))
      - traefik.http.routers.odoo-im-https.entrypoints=https
      - traefik.http.routers.odoo-im-https.service=odoo-im
      - traefik.http.routers.odoo-im-https.tls.certresolver=le
      - traefik.http.routers.odoo-im-https.middlewares=gzip,sslheader,limit

      #====================================================== services ===========================================================
      - traefik.http.services.odoo.loadbalancer.server.port=${ODOO_PORT}
      - traefik.http.services.odoo-im.loadbalancer.server.port=${CHAT_PORT}

      #===================================================== middlewares =========================================================
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=20971520
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=20971520
